### ISSUE TITLE
Snake is never ending. I'm scared for my life now

### ISSUE THREAD

**Issue by ktkaushik** [sankalpsans/css-snake#1]
<img width="1280" alt="screen shot 2015-11-06 at 12 57 05 am" src="https://cloud.githubusercontent.com/assets/877806/10979244/6653a4ce-8421-11e5-978f-d4fceba0067a.png">

**Comment by ktkaushik** [comment]
:)

**Comment by sankalpsans** [comment]
Haha. I'm working on a fix. This was built in sort of a hack-sprint of an hour.

**Comment by ktkaushik** [comment]
:+1:

**Comment by sankalpsans** [comment]
Fixed in this commit https://github.com/sankalpsans/css-snake/commit/b8e960be67f0e6d3a9575f4be462a37fa81ecba8

**Comment by ktkaushik** [comment]
:+1:
